### PR TITLE
Update repo

### PR DESCRIPTION
**Pull request by zimbatm**
What do you think of this approach to manage the git rev and sha256? (i guess only the last and previous-last commits are interesting)

### CODE REVIEW

**Comment by garbas** [comment]
+1 on generating this via script and reading it from json file

could we still have servoSrc? that would make it easy to integrate with hydra.


also would it make sense to have all sources in one place?
to have ``sources.json`` which would look like

```json
{
  "servo": {
    "owner": "servo",
    "repo": "servo",
    "rev": "b577d66ec374811a6493e95b37829269bbc97dfa",
    "sha256": "13jqfh7b87ss5yf9c4yl7cggawjm6w4hd8aq0q275adjzdmazz14"
  },
  "gecko": { ...}
}
```

/cc @nbp

**Comment by zimbatm** [comment]
Fixed it so that servoSrc can optionally be passed.

Is there any relationship between servo and gecko? Otherwise I would keep them in separated files. We could also potentially add all the long-running branches to both projects if that's useful.

**Comment by garbas** [comment]
there is no relationship (they are separate projects). lets leave their sources files separate for now.

i'm not sure what exactly you mean by "add all the long-running branches to both projects if that's useful."

**Comment by garbas** [comment]
i've merged but lets keep the conversation

**Comment by zimbatm** [comment]
Yeah I guess it's going to be easier to discuss with specific problems in mind.

**Pull request merged**
